### ISSUE TITLE
Is Readme correct ? `import { VuexSaga } from 'vuex-saga';`

### ISSUE THREAD

**Issue by alex-shamshurin** [niklv/vuex-coolstory#1]
maybe wrong import. It should be from 'vuex-coolstory', isn't it?

**Comment by niklv** [comment]
@alex-shamshurin No, it is correct. All works fine, you can run examples.
Also you can check code https://github.com/Niklv/vuex-coolstory/blob/master/index.js#L42

**Comment by wahabtobibello** [comment]
@Niklv How is it correct?
Does one have to install `vuex-saga` as well or `vuex-saga` references `vuex-coolstory` some  how?

**Comment by niklv** [comment]
@wahaaabello yep it is wrong( Fix it. It must be:
`import { VuexSaga } from 'vuex-coolstory';`
